name: "Docker Buildx Bake"
description: "GitHub Action to use Docker Buildx Bake as a high-level build command"
author: 'soramitsukhmer'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  images:
    description: 'List of Docker images to use as base name for tags'
    required: true
  targets:
    description: "List of bake targets"
    required: false
  pull:
    description: Always attempt to pull a newer version of the image (default false)
    required: false
    default: 'false'
  push:
    description: "Push is a shorthand for --set=*.output=type=registry"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.images }}
        tags: |
          type=sha
          type=schedule
          type=ref,event=pr
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    # Extract GitHub Action metadata for Docker
    # https://github.com/dockerbakery/github-metadata-action
    - name: Extract GitHub Docker metadata
      id: github-meta
      uses: dockerbakery/github-metadata-action@v1

    # Build and push Docker image with Buildx Bake
    # https://github.com/docker/bake-action
    - name: Build and push Docker image
      if: hashFiles('docker-bake.hcl') != ''
      uses: docker/bake-action@v2
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
          ${{ steps.github-meta.outputs.bake-file }}
        targets: ${{ inputs.targets }}
        push: ${{ inputs.push }}
        pull: ${{ inputs.pull }}
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
