name: "Generate Docker Bake Definition"
description: "GitHub Action to generate Docker Buildx Bake definition"
author: 'soramitsukhmer'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  target:
    description: Set generated target for Docker Bake Definition
    required: false
    default: 'build'

runs:
  using: "composite"
  steps:
    - name: Generate Docker Bake Definition
      shell: bash
      if: hashFiles('docker-bake.hcl') == ''
      run: |
        cat <<EOF > docker-bake.hcl
        target "docker-metadata-action" {}
        target "github-metadata-action" {}

        target "${{ inputs.target }}" {
          inherits = ["docker-metadata-action", "github-metadata-action"]
          context = "./"
          dockerfile = "Dockerfile"
          platforms = [
            "linux/amd64",
            "linux/arm64"
          ]
        }
        EOF
