name: test

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Docker Bake Definition
        uses: ./create-bake

      - name: Inspect docker-bake.hcl
        run: cat docker-bake.hcl

      - name: Generate Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM alpine:3.14
          EOF

      - name: Inspect Dockerfile
        run: cat Dockerfile

      - name: Build and Publish to Docker
        uses: ./
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          targets: build
          push: false
